### ISSUE TITLE
Sugestões para melhoria de arquitetura e performance

### ISSUE THREAD

**Issue by wbruno** [lffranca/api-teste-selecao-herakles#3]
sugestões:
- [ ] não crie funções dentro de outras funções
  https://github.com/lffranca/api-teste-selecao-herakles/blob/master/src/modules/postit/controller.js#L32
- [ ] não use o antipattern do segundo argumento do .then(), prefira sempre usar .catch
  https://github.com/lffranca/api-teste-selecao-herakles/blob/master/src/modules/postit/controller.js#L52
- [ ] melhor regex do que LIKE
  https://github.com/lffranca/api-teste-selecao-herakles/blob/master/src/modules/postit/controller.js#L110
- [ ] num projeto express envie os erros para o `next()` e trate os num único ponto da app
  https://github.com/lffranca/api-teste-selecao-herakles/blob/master/src/modules/postit/controller.js#L53
- [ ] módulo debug em vez de console.log
  https://github.com/lffranca/api-teste-selecao-herakles/blob/master/src/modules/postit/controller.js#L12
- [ ] anti pattern de fazer promises na mão (use promisify)
  https://github.com/lffranca/api-teste-selecao-herakles/blob/master/src/modules/postit/controller.js#L68 
- [ ] não injete req,res para fora do controller
  https://github.com/lffranca/api-teste-selecao-herakles/blob/master/src/modules/auth/controller.js#L92
- [ ] em vez de:

```
router.post('/', function(req, res) {
    Ctrl.create(req,res);
});
```

use:

```
router.post('/', Ctrl.create);
```

afinal, é javascript.
- [ ] não se esqueça de tratar os possíveis erros para tua app não morrer.
  https://github.com/lffranca/api-teste-selecao-herakles/blob/master/src/modules/user/controller.js#L17

**Comment by lffranca** [comment]
Legal @wbruno , gostei vou adotar todas as sugestões, só gostaria de saber como eu faria no primeiro caso, qual seria a alternativa para não criar funções dentro de funções?

**Comment by wbruno** [comment]
nesse caso ali, é só mover para fora daquele método.
